# deploy

NAME
----
deploy - deploy a project

USAGE
-----
command `deploy [command options] [arguments...]`

OPTIONS
-------

--project-dir::
  path where downloaded projects live
  Default;;
    ./_projects
--step-dir::
  path where downloaded steps live
  Default;;
    ./_steps
--build-dir::
  path where created builds live
  Default;;
    ./_builds
--container-dir::
  path where exported containers live
  Default;;
    ./_containers
--build-id::
  build id
--deploy-id::
  deploy id
--deploy-target::
  deploy target name
--application-id::
  application id
--application-name::
  application id
--application-owner-name::
  application id
--application-started-by-name::
  application started by
--pipeline::
  alternate pipeline name to execute
--docker-host::
  docker api host
  Default;;
    tcp://127.0.0.1:2375
--docker-tls-verify::
  docker api tls verify
  Default;;
    0
--docker-cert-path::
  docker api cert path
--direct-mount::
  mount our binds read-write to the pipeline path
--publish::
  publish a port from the main container, same format as docker --publish
--attach::
  Attach shell to container if a step fails.
--git-domain::
  git domain
--git-owner::
  git owner
--git-repository::
  git repository
--git-branch::
  git branch
--git-commit::
  git commit
--commit::
  commit the build result locally
--tag::
  tag for this build
--message::
  message for this build
--artifacts::
  store artifacts
--no-remove::
  don't remove the containers
--store-local::
  store artifacts and containers locally
--store-s3::
  store artifacts and containers on s3.
   This requires access to aws credentials, pulled from any of the usual places
   (~/.aws/config, AWS_SECRET_ACCESS_KEY, etc), or from the --aws-secret-key and
   --aws-access-key flags. It will upload to a bucket defined by --s3-bucket in
   the region named by --aws-region
--aws-secret-key::
  secret access key
--aws-access-key::
  access key id
--s3-bucket::
  bucket for artifacts
  Default;;
    wercker-development
--aws-region::
  region
  Default;;
    us-east-1
--source-dir::
  source path relative to checkout root
--no-response-timeout::
  timeout if no script output is received in this many minutes
  Default;;
    5.00
--command-timeout::
  timeout if command does not complete in this many minutes
  Default;;
    25.00
--wercker-yml::
  specify a specific yaml file
--mnt-root::
  directory on the guest where volumes are mounted
  Default;;
    /mnt
--guest-root::
  directory on the guest where work is done
  Default;;
    /pipeline
--report-root::
  directory on the guest where reports will be written
  Default;;
    /report
--keen-metrics::
  report metrics to keen.io
--keen-project-write-key::
  keen write key
--keen-project-id::
  keen project id
--report::
  Report logs back to wercker (requires build-id, wercker-host, wercker-token)
--wercker-host::
  Wercker host to use for wercker reporter
--wercker-token::
  Wercker token to use for wercker reporter

